/** Code generated by vrpc. DO NOT EDIT. */

import type * as types from './types.js'

export interface ClientConfig {
  baseUrl: string
  fetch?: typeof globalThis.fetch
}

export class VrpcHttpError extends Error {
  constructor(public status: number, public body: string) {
    super("HTTP " + status + ": " + body)
  }
}

function buildQuery(req: Record<string, unknown>, keys: readonly string[]): string {
  const params = new URLSearchParams()
  for (const key of keys) {
    const value = req[key]
    if (value === undefined || value === null || value === '') continue
    params.set(key, String(value))
  }
  const qs = params.toString()
  return qs ? '?' + qs : ''
}

async function request<T>(cfg: ClientConfig, init: RequestInit): Promise<T> {
  const f = cfg.fetch ?? globalThis.fetch
  const res = await f(cfg.baseUrl + init.url!, init)
  const text = await res.text()
  if (!res.ok) throw new VrpcHttpError(res.status, text)
  return text ? (JSON.parse(text) as T) : ({} as T)
}

export class UserClient {
  constructor(private readonly cfg: ClientConfig) {}

  async createUser(req: types.CreateUserRequest): Promise<types.CreateUserResponse> {
    return request<types.CreateUserResponse>(this.cfg, {
      method: 'POST',
      url: `/users`,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(req),
    })
  }


  async getUser(req: types.GetUserRequest): Promise<types.GetUserResponse> {
    return request<types.GetUserResponse>(this.cfg, {
      method: 'GET',
      url: `/users/${req.id}`,
    })
  }


  async listUsers(req: types.ListUsersRequest): Promise<types.ListUsersResponse> {
    return request<types.ListUsersResponse>(this.cfg, {
      method: 'GET',
      url: `/users` + buildQuery(req as Record<string, unknown>, ['limit', 'cursor']),
    })
  }


}
