/** Code generated by vrpc. DO NOT EDIT. */

export interface CreateUserRequest {
  name: string
  email: string
}


export interface CreateUserResponse {
  id?: string
  name?: string
  email?: string
}


export interface GetUserRequest {
  id: string
}


export interface GetUserResponse {
  id?: string
  name?: string
  email?: string
}


export interface ListUsersRequest {
  limit?: number
  cursor?: string
}


export interface ListUsersResponse {
  users?: UserSummary[]
  next_cursor?: string
}


export interface UserSummary {
  id?: string
  name?: string
  email?: string
}


export interface ApiError {
  code: string
  message: string
  details?: Array<{ field: string; rule: string; message: string }>
}
