/** Code generated by vesper. DO NOT EDIT. */

import { z } from 'zod'

export const CreateUserRequestSchema = z.object({
  name: z.string().min(1),
  email: z.string().email()
})

export const CreateUserResponseSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  email: z.string().optional()
})

export const GetUserRequestSchema = z.object({
  id: z.string()
})

export const GetUserResponseSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  email: z.string().optional()
})

export const ListUsersRequestSchema = z.object({
  limit: z.number().int().min(1).max(100).optional(),
  cursor: z.string().optional()
})

export const ListUsersResponseSchema = z.object({
  users: z.array(UserSummarySchema).optional(),
  next_cursor: z.string().optional()
})

export const UserSummarySchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  email: z.string().optional()
})

