module main

import strings as strutil

pub fn emit_v_server(service Service) []GeneratedFile {
	return [GeneratedFile{
		path:    'generated.v'
		content: generate_v_server(service)
	}]
}

pub fn emit_v_client(service Service) []GeneratedFile {
	return [GeneratedFile{
		path:    'client.generated.v'
		content: generate_v_client(service)
	}]
}

fn generate_v_server(s Service) string {
	mut b := strutil.Builder{}
	b.writeln('// Code generated by vrpc. DO NOT EDIT.')
	b.writeln('module ${s.module}')
	b.writeln('')
	b.writeln('import vrpc')
	b.writeln('')
	for _, name in sorted_type_names(s) {
		st := s.types[name]
		b.writeln(v_schema_fn(st))
		b.writeln('')
	}
	for _, name in input_type_names(s) {
		st := s.types[name]
		b.writeln(v_bind_fn(st))
		b.writeln('')
		b.writeln(v_validate_fn(st))
		b.writeln('')
	}
	b.writeln('@[heap]')
	b.writeln('pub struct ${s.name}Runtime {')
	b.writeln('pub mut:')
	b.writeln('	impl ${v_impl_name(s.name)}')
	b.writeln('}')
	b.writeln('')
	mount := v_service_mount_name(s.name)
	b.writeln('pub fn ${mount}(mut app vrpc.App, impl ${v_impl_name(s.name)}) ! {')
	b.writeln('	mut rt := ${s.name}Runtime{ impl: impl }')
	b.writeln('	service := vrpc.ServiceDef{')
	b.writeln("		name: '${s.name}'")
	b.writeln("		prefix: '${s.prefix}'")
	b.writeln('		procedures: [')
	for proc in s.procedures {
		b.writeln('			vrpc.ProcedureDef{')
		b.writeln("				name: '${proc.name}'")
		b.writeln('				input_schema: ${v_schema_name(proc.input_type)}()')
		b.writeln('				output_schema: ${v_schema_name(proc.output_type)}()')
		b.writeln('				transport: vrpc.TransportBinding{')
		b.writeln('					method: .${proc.method.str()}')
		b.writeln("					path: '${proc.path}'")
		b.writeln('				}')
		b.writeln('				handler: rt.${proc.name}_handler')
		b.writeln('			},')
	}
	b.writeln('		]')
	b.writeln('	}')
	b.writeln('	app.register_service(service)!')
	b.writeln('}')
	b.writeln('')
	for proc in s.procedures {
		b.writeln(v_handler_method(s, proc))
		b.writeln('')
	}
	return b.str()
}

fn generate_v_client(s Service) string {
	mod := '${s.module}_client'
	mut b := strutil.Builder{}
	b.writeln('// Code generated by vrpc. DO NOT EDIT.')
	b.writeln('module ${mod}')
	b.writeln('')
	b.writeln('import json')
	b.writeln('import vrpc')
	b.writeln('import ${s.module}')
	b.writeln('')
	b.writeln('pub struct ClientConfig {')
	b.writeln('pub:')
	b.writeln('	base_url string')
	b.writeln('}')
	b.writeln('')
	b.writeln('pub struct Client {')
	b.writeln('pub:')
	b.writeln('	base_url string')
	b.writeln('}')
	b.writeln('')
	b.writeln('pub fn new(config ClientConfig) Client {')
	b.writeln('	return Client{ base_url: config.base_url }')
	b.writeln('}')
	b.writeln('')
	for proc in s.procedures {
		b.writeln(v_client_method(s, proc))
		b.writeln('')
	}
	return b.str()
}

fn sorted_type_names(s Service) []string {
	mut names := s.types.keys()
	names.sort()
	return names
}

fn input_type_names(s Service) []string {
	mut names := []string{}
	mut seen := map[string]bool{}
	for proc in s.procedures {
		if proc.input_type !in seen {
			seen[proc.input_type] = true
			names << proc.input_type
		}
	}
	names.sort()
	return names
}

fn v_impl_name(service_name string) string {
	return '${service_name}Impl'
}

fn v_client_method(s Service, proc Procedure) string {
	full_path := join_http_path(s.prefix, proc.path)
	mut b := strutil.Builder{}
	b.writeln('pub fn (c Client) ${proc.name}(req ${s.module}.${proc.input_type}) !${s.module}.${proc.output_type} {')
	match proc.method {
		.get {
			b.writeln("	body := vrpc.client_get(c.base_url + '${full_path}')!")
		}
		else {
			b.writeln("	body := vrpc.client_post_json(c.base_url + '${full_path}', req)!")
		}
	}
	b.writeln('	return json.decode(${s.module}.${proc.output_type}, body)!')
	b.writeln('}')
	return b.str()
}

fn v_handler_method(s Service, proc Procedure) string {
	st_name := proc.input_type
	return "pub fn (mut r ${s.name}Runtime) ${proc.name}_handler(mut ctx vrpc.Context) !vrpc.Response {
	req := bind_${snake_case(st_name)}(mut ctx)!
	errs := validate_${snake_case(st_name)}(req)
	if errs.len > 0 {
		return vrpc.validation_error_response(errs)
	}
	res := r.impl.${proc.name}(req)!
	return vrpc.json_response(res)
}"
}

fn v_bind_fn(st TypeDef) string {
	mut b := strutil.Builder{}
	b.writeln('pub fn bind_${snake_case(st.name)}(mut ctx vrpc.Context) !${st.name} {')
	mut has_body := false
	for f in st.fields {
		if f.source == .body {
			has_body = true
		}
	}
	if has_body {
		b.writeln('	mut decoded := vrpc.bind_body[${st.name}](ctx)!')
	} else {
		b.writeln('	mut decoded := ${st.name}{}')
	}
	for f in st.fields {
		match f.source {
			.path {
				b.writeln('	decoded.${f.name} = vrpc.bind_path_param(ctx, \'${f.name}\')')
			}
			.query {
				if f.kind == .int {
					b.writeln('	decoded.${f.name} = vrpc.query_int(ctx, \'${f.name}\', 0)')
				} else {
					b.writeln('	decoded.${f.name} = vrpc.bind_query_param(ctx, \'${f.name}\')')
				}
			}
			.header {
				key := if f.header_key != '' { f.header_key } else { f.name }
				b.writeln('	decoded.${f.name} = vrpc.bind_header(ctx, \'${key}\')')
			}
			else {}
		}
	}
	b.writeln('	return decoded')
	b.writeln('}')
	return b.str()
}

fn v_validate_fn(st TypeDef) string {
	mut b := strutil.Builder{}
	b.writeln('fn validate_${snake_case(st.name)}(req ${st.name}) []vrpc.ValidationError {')
	b.writeln('	mut errs := []vrpc.ValidationError{}')
	for f in st.fields {
		if f.kind == .int {
			b.writeln('	errs = vrpc.merge_errors(mut errs, vrpc.validate_int_field(\'${f.name}\', req.${f.name}, ${v_validators_literal(f)}))')
		} else {
			b.writeln('	errs = vrpc.merge_errors(mut errs, vrpc.validate_field(\'${f.name}\', req.${f.name}, ${v_validators_literal(f)}))')
		}
	}
	b.writeln('	return vrpc.collect_errors(errs)')
	b.writeln('}')
	return b.str()
}

fn v_validators_literal(f Field) string {
	mut parts := []string{}
	if f.required {
		parts << 'vrpc.ValidatorDef{ rule: \'required\', value: \'\' }'
	}
	for v in f.validators {
		if v.rule != 'required' {
			parts << 'vrpc.ValidatorDef{ rule: \'${v.rule}\', value: \'${v.value}\' }'
		}
	}
	if parts.len == 0 {
		return '[]vrpc.ValidatorDef{}'
	}
	return '[${parts.join(', ')}]'
}

fn v_schema_fn(st TypeDef) string {
	mut b := strutil.Builder{}
	b.writeln('fn ${v_schema_name(st.name)}() vrpc.Schema {')
	b.writeln('	return vrpc.object_schema(\'${st.name}\', [')
	for f in st.fields {
		b.writeln('		vrpc.SchemaField{')
		b.writeln("			name: '${f.name}'")
		b.writeln("			typ: '${v_vtype_name(f)}'")
		b.writeln('			source: .${f.source.str()}')
		b.writeln('			required: ${f.required}')
		b.writeln('			validators: ${v_validators_literal(f)}')
		b.writeln('		},')
	}
	b.writeln('	])')
	b.writeln('}')
	return b.str()
}

fn (s FieldSource) str() string {
	return match s {
		.body { 'body' }
		.path { 'path' }
		.query { 'query' }
		.header { 'header' }
	}
}

fn v_vtype_name(f Field) string {
	if f.kind == .array {
		return '[]${f.array_elem}'
	}
	return match f.kind {
		.int { 'int' }
		.bool { 'bool' }
		.f64 { 'f64' }
		else { 'string' }
	}
}

fn v_schema_name(type_name string) string {
	return 'schema_${snake_case(type_name)}'
}

fn v_service_mount_name(service_name string) string {
	base := service_base_name(service_name)
	return 'mount_${snake_case(base)}_service'
}
