module main

import strings as strutil

pub fn emit_ts_zod(service Service) GeneratedFile {
	base := service_base_name(service.name)
	pkg := snake_case(base)
	return GeneratedFile{
		path:    '${pkg}/schemas.zod.ts'
		content: generate_zod_schemas(service)
	}
}

fn generate_zod_schemas(s Service) string {
	mut b := strutil.Builder{}
	b.writeln('/** Code generated by vesper. DO NOT EDIT. */')
	b.writeln('')
	b.writeln("import { z } from 'zod'")
	b.writeln('')
	for _, name in sorted_type_names(s) {
		st := s.types[name]
		b.writeln(zod_schema(st, s.types))
		b.writeln('')
	}
	return b.str()
}

fn zod_schema(st TypeDef, all map[string]TypeDef) string {
	mut fields := []string{}
	for f in st.fields {
		fields << '  ${f.name}: ${zod_field_expr(f, all)}'
	}
	return 'export const ${st.name}Schema = z.object({\n${fields.join(',\n')}\n})'
}

fn zod_field_expr(f Field, all map[string]TypeDef) string {
	mut expr := zod_base_expr(f, all)
	for v in f.validators {
		expr = zod_apply_validator(expr, v, f.kind)
	}
	if !f.required {
		expr += '.optional()'
	}
	return expr
}

fn zod_base_expr(f Field, all map[string]TypeDef) string {
	if f.kind == .array {
		inner := zod_named_ref(f.array_elem, all)
		return 'z.array(${inner})'
	}
	return match f.kind {
		.int { 'z.number().int()' }
		.f64 { 'z.number()' }
		.bool { 'z.boolean()' }
		else { 'z.string()' }
	}
}

fn zod_named_ref(name string, all map[string]TypeDef) string {
	if name in all {
		return '${name}Schema'
	}
	return 'z.string()'
}

fn zod_apply_validator(expr string, v Validator, kind TypeKind) string {
	return match v.rule {
		'email' { '${expr}.email()' }
		'uuid' { '${expr}.uuid()' }
		'min_len' { '${expr}.min(${v.value})' }
		'max_len' { '${expr}.max(${v.value})' }
		'min' {
			if kind == .int {
				'${expr}.min(${v.value})'
			} else {
				expr
			}
		}
		'max' {
			if kind == .int {
				'${expr}.max(${v.value})'
			} else {
				expr
			}
		}
		else { expr }
	}
}
