module main

import strings as strutil

pub fn emit_ts_client(service Service, opts TsEmitOptions) []GeneratedFile {
	base := service_base_name(service.name)
	pkg := snake_case(base)
	mut files := [
		GeneratedFile{
			path:    '${pkg}/types.ts'
			content: generate_ts_types(service)
		},
		GeneratedFile{
			path:    '${pkg}/client.ts'
			content: generate_ts_client(service)
		},
		GeneratedFile{
			path:    '${pkg}/index.ts'
			content: generate_ts_index(service, opts.zod)
		},
	]
	if opts.zod {
		files << emit_ts_zod(service)
	}
	return files
}

pub struct TsEmitOptions {
pub:
	zod bool
}

fn generate_ts_types(s Service) string {
	mut b := strutil.Builder{}
	b.writeln('/** Code generated by vesper. DO NOT EDIT. */')
	b.writeln('')
	for _, name in sorted_type_names(s) {
		b.writeln(ts_interface(s.types[name]))
		b.writeln('')
	}
	b.writeln('export interface ApiError {')
	b.writeln('  code: string')
	b.writeln('  message: string')
	b.writeln('  details?: Array<{ field: string; rule: string; message: string }>')
	b.writeln('}')
	return b.str()
}

fn generate_ts_client(s Service) string {
	base := service_base_name(s.name)
	class_name := '${base}Client'
	mut b := strutil.Builder{}
	b.writeln('/** Code generated by vesper. DO NOT EDIT. */')
	b.writeln('')
	b.writeln("import type * as types from './types.js'")
	b.writeln('')
	b.writeln('export interface ClientConfig {')
	b.writeln('  baseUrl: string')
	b.writeln('  fetch?: typeof globalThis.fetch')
	b.writeln('}')
	b.writeln('')
	b.writeln('export class VesperHttpError extends Error {')
	b.writeln('  constructor(public status: number, public body: string) {')
	b.writeln('    super("HTTP " + status + ": " + body)')
	b.writeln('  }')
	b.writeln('}')
	b.writeln('')
	b.writeln('function buildQuery(req: Record<string, unknown>, keys: readonly string[]): string {')
	b.writeln('  const params = new URLSearchParams()')
	b.writeln('  for (const key of keys) {')
	b.writeln('    const value = req[key]')
	b.writeln("    if (value === undefined || value === null || value === '') continue")
	b.writeln('    params.set(key, String(value))')
	b.writeln('  }')
	b.writeln('  const qs = params.toString()')
	b.writeln("  return qs ? '?' + qs : ''")
	b.writeln('}')
	b.writeln('')
	b.writeln('async function request<T>(cfg: ClientConfig, init: RequestInit): Promise<T> {')
	b.writeln('  const f = cfg.fetch ?? globalThis.fetch')
	b.writeln('  const res = await f(cfg.baseUrl + init.url!, init)')
	b.writeln('  const text = await res.text()')
	b.writeln('  if (!res.ok) throw new VesperHttpError(res.status, text)')
	b.writeln('  return text ? (JSON.parse(text) as T) : ({} as T)')
	b.writeln('}')
	b.writeln('')
	b.writeln('export class ${class_name} {')
	b.writeln('  constructor(private readonly cfg: ClientConfig) {}')
	b.writeln('')
	for proc in s.procedures {
		b.writeln(ts_client_method(s, proc))
		b.writeln('')
	}
	b.writeln('}')
	return b.str()
}

fn generate_ts_index(s Service, include_zod bool) string {
	base := service_base_name(s.name)
	mut b := strutil.Builder{}
	b.writeln('/** Code generated by vesper. DO NOT EDIT. */')
	b.writeln("export * from './types.js'")
	b.writeln("export { ${base}Client, VesperHttpError, type ClientConfig } from './client.js'")
	if include_zod {
		b.writeln("export * from './schemas.zod.js'")
	}
	return b.str()
}

fn ts_interface(st TypeDef) string {
	mut b := strutil.Builder{}
	b.writeln('export interface ${st.name} {')
	for f in st.fields {
		opt := if f.required { '' } else { '?' }
		b.writeln('  ${f.name}${opt}: ${ts_field_type(f)}')
	}
	b.writeln('}')
	return b.str()
}

fn ts_field_type(f Field) string {
	if f.kind == .array {
		return '${f.array_elem}[]'
	}
	return ts_type_name(match f.kind {
		.int { 'int' }
		.bool { 'bool' }
		.f64 { 'f64' }
		else { 'string' }
	})
}

fn ts_type_name(vtyp string) string {
	return match vtyp {
		'int' { 'number' }
		'bool' { 'boolean' }
		'f64' { 'number' }
		else { 'string' }
	}
}

fn ts_client_method(s Service, proc Procedure) string {
	input := s.types[proc.input_type] or { TypeDef{ name: proc.input_type } }
	method := proc.method.upper()
	path_template := path_to_template(s.prefix, proc.path)
	mut b := strutil.Builder{}
	b.writeln('  async ${camel_case(proc.name)}(req: types.${proc.input_type}): Promise<types.${proc.output_type}> {')
	path_expr := ts_path_expr(path_template, input)
	query_expr := ts_query_expr(input)
	body_expr := ts_body_expr(proc.method, input)
	b.writeln('    return request<types.${proc.output_type}>(this.cfg, {')
	b.writeln("      method: '${method}',")
	b.writeln('      url: ${path_expr}${query_expr},')
	if body_expr != '' {
		b.writeln('      headers: { \'Content-Type\': \'application/json\' },')
		b.writeln('      body: JSON.stringify(${body_expr}),')
	}
	b.writeln('    })')
	b.writeln('  }')
	return b.str()
}

fn ts_path_expr(template string, input TypeDef) string {
	mut t := template
	for f in input.fields {
		if f.source == .path {
			placeholder := '$' + '{' + f.name + '}'
			t = t.replace(placeholder, '$' + '{req.' + f.name + '}')
		}
	}
	return '`' + t + '`'
}

fn ts_query_expr(input TypeDef) string {
	mut keys := []string{}
	for f in input.fields {
		if f.source == .query {
			keys << "'${f.name}'"
		}
	}
	if keys.len == 0 {
		return ''
	}
	return ' + buildQuery(req as Record<string, unknown>, [${keys.join(', ')}])'
}

fn ts_body_expr(method HttpMethod, input TypeDef) string {
	if method == .get {
		return ''
	}
	mut body_fields := []string{}
	for f in input.fields {
		if f.source == .body {
			body_fields << f.name
		}
	}
	if body_fields.len == 0 {
		return 'req'
	}
	if body_fields.len == input.fields.len {
		return 'req'
	}
	mut pairs := []string{}
	for name in body_fields {
		pairs << '${name}: req.${name}'
	}
	return '{ ${pairs.join(', ')} }'
}
