// Code generated by vesper. DO NOT EDIT.
module users_client

import json
import vesper
import users

pub struct ClientConfig {
pub:
	base_url string
}

pub struct Client {
pub:
	base_url string
}

pub fn new(config ClientConfig) Client {
	return Client{ base_url: config.base_url }
}

pub fn (c Client) create_user(req users.CreateUserRequest) !users.CreateUserResponse {
	body := vesper.client_post_json(c.base_url + '/users/', req)!
	return json.decode(users.CreateUserResponse, body)!
}

pub fn (c Client) get_user(id string) !users.GetUserResponse {
	body := vesper.client_get('${c.base_url}/users/${id}')!
	return json.decode(users.GetUserResponse, body)!
}

pub fn (c Client) list_users(limit int, cursor string) !users.ListUsersResponse {
	url := '${c.base_url}/users/?limit=${limit}&cursor=${cursor}'
	body := vesper.client_get(url)!
	return json.decode(users.ListUsersResponse, body)!
}
